///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace eCommerceTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddCart recording.
    /// </summary>
    [TestModule("760c0a2a-c6da-4974-bd8f-baaa5b87f081", ModuleType.Recording, 1)]
    public partial class AddCart : ITestModule
    {
        /// <summary>
        /// Holds an instance of the eCommerceTestRepository repository.
        /// </summary>
        public static eCommerceTestRepository repo = eCommerceTestRepository.Instance;

        static AddCart instance = new AddCart();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddCart()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddCart Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // Move on supermarket button.
            Report.Log(ReportLevel.Info, "Mouse", "Move on supermarket button.\r\nMouse Left Move item 'ApplicationUnderTest.Suepermarket' at 130;26.", repo.ApplicationUnderTest.SuepermarketInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.Suepermarket.MoveTo("130;26");
            Delay.Milliseconds(0);
            
            // Click kahve button.
            Report.Log(ReportLevel.Info, "Mouse", "Click kahve button.\r\nMouse Left Click item 'ApplicationUnderTest.Kahve' at 30;14.", repo.ApplicationUnderTest.KahveInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.Kahve.Click("30;14");
            Delay.Milliseconds(0);
            
            // Click add to cart button.
            Report.Log(ReportLevel.Info, "Mouse", "Click add to cart button.\r\nMouse Left Click item 'ApplicationUnderTest.BtnBasket.AddToBasketButton' at 46;4.", repo.ApplicationUnderTest.BtnBasket.AddToBasketButtonInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.BtnBasket.AddToBasketButton.Click("46;4");
            Delay.Milliseconds(0);
            
            // Wait for add to cart task is done.
            Report.Log(ReportLevel.Info, "Wait", "Wait for add to cart task is done.\r\nWaiting 10s for the attribute 'Class' to equal the specified value 'add-to-basket-button success'. Associated repository item: 'ApplicationUnderTest.BtnBasket.AddToBasketButton'", repo.ApplicationUnderTest.BtnBasket.AddToBasketButtonInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.BtnBasket.AddToBasketButtonInfo.WaitForAttributeEqual(10000, "Class", "add-to-basket-button success");
            
            // Valitade add to cart task is done.
            Report.Log(ReportLevel.Info, "Validation", "Valitade add to cart task is done.\r\nValidating AttributeEqual (Class='add-to-basket-button success') on item 'ApplicationUnderTest.BtnBasket.AddToBasketButton'.", repo.ApplicationUnderTest.BtnBasket.AddToBasketButtonInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.ApplicationUnderTest.BtnBasket.AddToBasketButtonInfo, "Class", "add-to-basket-button success");
            Delay.Milliseconds(100);
            
            // Click add to cart button.
            Report.Log(ReportLevel.Info, "Mouse", "Click add to cart button.\r\nMouse Left Click item 'ApplicationUnderTest.AddToBasketButton' at 342;8.", repo.ApplicationUnderTest.AddToBasketButtonInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.AddToBasketButton.Click("342;8");
            Delay.Milliseconds(0);
            
            // Wait for add to cart task is done.
            Report.Log(ReportLevel.Info, "Wait", "Wait for add to cart task is done.\r\nWaiting 10s for the attribute 'Class' to equal the specified value 'add-to-basket-button success'. Associated repository item: 'ApplicationUnderTest.AddToBasketButton'", repo.ApplicationUnderTest.AddToBasketButtonInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.AddToBasketButtonInfo.WaitForAttributeEqual(10000, "Class", "add-to-basket-button success");
            
            // Valitade add to cart task is done.
            Report.Log(ReportLevel.Info, "Validation", "Valitade add to cart task is done.\r\nValidating AttributeEqual (Class='add-to-basket-button success') on item 'ApplicationUnderTest.AddToBasketButton'.", repo.ApplicationUnderTest.AddToBasketButtonInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AddToBasketButtonInfo, "Class", "add-to-basket-button success");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
