///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace eCommerceTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BuyVerify recording.
    /// </summary>
    [TestModule("973125fc-f607-4852-a05a-b0d94fb657ce", ModuleType.Recording, 1)]
    public partial class BuyVerify : ITestModule
    {
        /// <summary>
        /// Holds an instance of the eCommerceTestRepository repository.
        /// </summary>
        public static eCommerceTestRepository repo = eCommerceTestRepository.Instance;

        static BuyVerify instance = new BuyVerify();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BuyVerify()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BuyVerify Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // Move on sepetim button.
            Report.Log(ReportLevel.Info, "Mouse", "Move on sepetim button.\r\nMouse Left Move item 'ApplicationUnderTest.Sepetim' at 54;12.", repo.ApplicationUnderTest.SepetimInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.Sepetim.MoveTo("54;12");
            Delay.Milliseconds(0);
            
            // Wait for sparisi tamamla button appear.
            Report.Log(ReportLevel.Info, "Wait", "Wait for sparisi tamamla button appear.\r\nWaiting 5s to exist. Associated repository item: 'ApplicationUnderTest.SiparişiTamamla'", repo.ApplicationUnderTest.SiparişiTamamlaInfo, new ActionTimeout(5000), new RecordItemIndex(1));
            repo.ApplicationUnderTest.SiparişiTamamlaInfo.WaitForExists(5000);
            
            // Click sparisi tamamla button.
            Report.Log(ReportLevel.Info, "Mouse", "Click sparisi tamamla button.\r\nMouse Left Click item 'ApplicationUnderTest.SiparişiTamamla' at 114;40.", repo.ApplicationUnderTest.SiparişiTamamlaInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.SiparişiTamamla.Click("114;40");
            Delay.Milliseconds(0);
            
            // Click close cross.
            try {
                Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nClick close cross.\r\nMouse Left Click item 'ApplicationUnderTest.TyCross' at 16;10.", repo.ApplicationUnderTest.TyCrossInfo, new RecordItemIndex(3));
                repo.ApplicationUnderTest.TyCross.ClickWithoutBoundsCheck("16;10");
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(3)); }
            
            // Click trendyol amblem.
            Report.Log(ReportLevel.Info, "Mouse", "Click trendyol amblem.\r\nMouse Left Click item 'ApplicationUnderTest.HttpsCdnDsmcdnComWebProductionTy' at 182;54.", repo.ApplicationUnderTest.HttpsCdnDsmcdnComWebProductionTyInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.HttpsCdnDsmcdnComWebProductionTy.Click("182;54");
            Delay.Milliseconds(9180);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
