///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace eCommerceTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The EmptyErrorVerify recording.
    /// </summary>
    [TestModule("52d8fa9c-d774-4477-837c-bbab1b9f6256", ModuleType.Recording, 1)]
    public partial class EmptyErrorVerify : ITestModule
    {
        /// <summary>
        /// Holds an instance of the eCommerceTestRepository repository.
        /// </summary>
        public static eCommerceTestRepository repo = eCommerceTestRepository.Instance;

        static EmptyErrorVerify instance = new EmptyErrorVerify();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public EmptyErrorVerify()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static EmptyErrorVerify Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // Validate e-mail field is empty.
            Report.Log(ReportLevel.Info, "Validation", "Validate e-mail field is empty.\r\nValidating AttributeEqual (Value='') on item 'ApplicationUnderTest.RegisterEmail'.", repo.ApplicationUnderTest.RegisterEmailInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.ApplicationUnderTest.RegisterEmailInfo, "Value", "");
            Delay.Milliseconds(100);
            
            // Validate password field is empty.
            Report.Log(ReportLevel.Info, "Validation", "Validate password field is empty.\r\nValidating AttributeEqual (Value='') on item 'ApplicationUnderTest.RegisterPasswordInput'.", repo.ApplicationUnderTest.RegisterPasswordInputInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.ApplicationUnderTest.RegisterPasswordInputInfo, "Value", "");
            Delay.Milliseconds(100);
            
            // Validate personal checkbox field is empty.
            Report.Log(ReportLevel.Info, "Validation", "Validate personal checkbox field is empty.\r\nValidating AttributeEqual (TagValue='false') on item 'ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.TyBgBeigeTyBorderedTyCheckboxTyI2'.", repo.ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.TyBgBeigeTyBorderedTyCheckboxTyI2Info, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.TyBgBeigeTyBorderedTyCheckboxTyI2Info, "TagValue", "false");
            Delay.Milliseconds(100);
            
            // Click submit button.
            Report.Log(ReportLevel.Info, "Mouse", "Click submit button.\r\nMouse Left Click item 'ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.QButtonQButtonMediumQFluidQPrima' at 251;32.", repo.ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.QButtonQButtonMediumQFluidQPrimaInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.QButtonQButtonMediumQFluidQPrima.Click("251;32");
            Delay.Milliseconds(0);
            
            // Validate validation error is exist.
            Report.Log(ReportLevel.Info, "Validation", "Validate validation error is exist.\r\nValidating Exists on item 'ApplicationUnderTest.ErrorBoxWrapper'.", repo.ApplicationUnderTest.ErrorBoxWrapperInfo, new RecordItemIndex(4));
            Validate.Exists(repo.ApplicationUnderTest.ErrorBoxWrapperInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
