///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace eCommerceTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The PresentVerify recording.
    /// </summary>
    [TestModule("a9d5ff35-adbe-4b1c-a09e-f80bc8f40e47", ModuleType.Recording, 1)]
    public partial class PresentVerify : ITestModule
    {
        /// <summary>
        /// Holds an instance of the eCommerceTestRepository repository.
        /// </summary>
        public static eCommerceTestRepository repo = eCommerceTestRepository.Instance;

        static PresentVerify instance = new PresentVerify();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public PresentVerify()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static PresentVerify Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // Validate e-mail field is exist.
            Report.Log(ReportLevel.Info, "Validation", "Validate e-mail field is exist.\r\nValidating Exists on item 'ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.EmailInputQInputWrapper'.", repo.ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.EmailInputQInputWrapperInfo, new RecordItemIndex(0));
            Validate.Exists(repo.ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.EmailInputQInputWrapperInfo);
            Delay.Milliseconds(100);
            
            // Validate password field is exist.
            Report.Log(ReportLevel.Info, "Validation", "Validate password field is exist.\r\nValidating Exists on item 'ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.PasswordWrapper'.", repo.ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.PasswordWrapperInfo, new RecordItemIndex(1));
            Validate.Exists(repo.ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.PasswordWrapperInfo);
            Delay.Milliseconds(100);
            
            // Validate gender flexflex field is exist.
            Report.Log(ReportLevel.Info, "Validation", "Validate gender flexflex field is exist.\r\nValidating Exists on item 'ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.FlexFlexColumnGender'.", repo.ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.FlexFlexColumnGenderInfo, new RecordItemIndex(2));
            Validate.Exists(repo.ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.FlexFlexColumnGenderInfo);
            Delay.Milliseconds(100);
            
            // Validate marketing checkbox field is exist.
            Report.Log(ReportLevel.Info, "Validation", "Validate marketing checkbox field is exist.\r\nValidating Exists on item 'ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.MarketingCheckbox'.", repo.ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.MarketingCheckboxInfo, new RecordItemIndex(3));
            Validate.Exists(repo.ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.MarketingCheckboxInfo);
            Delay.Milliseconds(100);
            
            // Validate personal checkbox field is exist.
            Report.Log(ReportLevel.Info, "Validation", "Validate personal checkbox field is exist.\r\nValidating Exists on item 'ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.PersonalCheckbox'.", repo.ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.PersonalCheckboxInfo, new RecordItemIndex(4));
            Validate.Exists(repo.ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.PersonalCheckboxInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
