///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace eCommerceTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Unfav recording.
    /// </summary>
    [TestModule("ce02acc2-87d3-40b1-b158-bff030cd44fb", ModuleType.Recording, 1)]
    public partial class Unfav : ITestModule
    {
        /// <summary>
        /// Holds an instance of the eCommerceTestRepository repository.
        /// </summary>
        public static eCommerceTestRepository repo = eCommerceTestRepository.Instance;

        static Unfav instance = new Unfav();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Unfav()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Unfav Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // Click favorite button.
            Report.Log(ReportLevel.Info, "Mouse", "Click favorite button.\r\nMouse Left Click item 'ApplicationUnderTest.FavoredProductContainer.FeaturedFv1' at 22;52.", repo.ApplicationUnderTest.FavoredProductContainer.FeaturedFv1Info, new RecordItemIndex(0));
            repo.ApplicationUnderTest.FavoredProductContainer.FeaturedFv1.Click("22;52");
            Delay.Milliseconds(0);
            
            // Click favorite button.
            Report.Log(ReportLevel.Info, "Mouse", "Click favorite button.\r\nMouse Left Click item 'ApplicationUnderTest.FavoredProductContainer.FeaturedFv' at 46;54.", repo.ApplicationUnderTest.FavoredProductContainer.FeaturedFvInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.FavoredProductContainer.FeaturedFv.Click("46;54");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
